.TH lcc 1 lcc\-1.0.0
.SH NAME
lcc \- Lines of Code Counter 
.SH SYNOPSIS
.B lcc

.SH DESCRIPTION
lcc is a fast and lightweight source lines of code counter.

.SH OPTIONS
.TP
.B apm <path> <path2> <path3>
Count lines of code in the supplied paths.

.SH AUTHOR
Made by Night Kaly
.B <night@night0721.xyz>
